<?php

/**
 * This module provides a simple way to create send out notifications and reminders (emails) to users about the webform.
 *
 * The initial development of this module was sponsered by IT-Kartellet ApS
 * http://www.it-kartellet.dk
 *
 * @author Henrik Thorn <henrikthorn@it-kartellet.dk>
 */

/**
 * Implements hook_menu().
 */
function webform_mailer_menu() {
  $items = array();

  // Node e-mail forms.
  $items['node/%webform_menu/webform/mailer'] = array(
    'title' => 'Webform Mailer - Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_mailer_settings_form', 1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'includes/webform_mailer.settings.inc',
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
  );

  // Node users forms.
  $items['node/%webform_menu/webform/users'] = array(
    'title' => 'Webform Mailer - Users',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_mailer_users_form', 1),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'includes/webform_mailer.users.inc',
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );

  $items['node/%webform_menu/webform/users/%webform_mailer_menu_role'] = array(
    'title' => 'Webform Mailer - Users Select',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_mailer_users_roles_form', 1, 4),
    'load arguments' => array(1, 4),
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'file' => 'includes/webform_mailer.users.inc',
    'type' => MENU_CALLBACK,
  );

  $items['node/%webform_menu/token/%'] = array(
    'title' => 'Webform Token',
    'page callback' => 'get_confirm',
    'page arguments' => array(1, 3),
    'file' => 'includes/webform_mailer.token.inc',
    'access callback' => 'node_access',
    'access arguments' => array('update', 1),
    'type' => MENU_CALLBACK,
  );

return $items;
}

function webform_mailer_menu_role_load($roles){

	$roles = explode('-', $roles);

	foreach($roles as $role){
		$export[] = user_role_load($role); 
	}
	return $export;
}
function webform_mailer_webform_submission_presave($node, &$submission) {
  	// Update some component's value before it is saved.
  	global $user;
	
	        $query = db_update('webform_mailer_users')
                ->fields(array(
                  'status' => 'finished'
                ))
                ->condition('nid', $node->nid)
                ->condition('uid', $user->uid)
                ->execute();

}

function webform_mailer_cron(){

	$db_mailer = db_query("SELECT DISTINCT * FROM webform_mailer WHERE sendmail = 1");
	
	foreach($db_mailer as $webform_mailer){
		$count = 0;
		$nid = $webform_mailer->nid;
		$reminders = $webform_mailer->reminders;		
		$status = null;
		$from = $webform_mailer->mail_from;

		if($webform_mailer->notify == 1 AND $webform_mailer->status == null){
			$db_users = db_query("SELECT DISTINCT * FROM webform_mailer_users u WHERE u.nid = ".$nid);
			
			foreach($db_users as $account){
				$params['account'] = $account;
				$params['webform'] = $webform_mailer;
				$user_details = get_user_details($account);
				drupal_mail('mailer', 'notify', $user_details->mail, user_preferred_language($account), $params, $from, TRUE);
				$query = db_insert('webform_mailer_messages')
				->fields(array(
				  'nid' => $nid,
				  'uid' => $account->uid,
				  'message_time' => time(),
				  'type' => 'notification',
				))->execute();		
			}
			
			$status = "notified";
		}
		if(($webform_mailer->status == "notified" && $webform_mailer->reminders >= 1) || ($webform_mailer->status == 'reminded' && $webform_mailer->reminders >=2)){
			$db_users = db_query("SELECT DISTINCT * FROM webform_mailer_users u INNER JOIN webform_mailer_messages m ON u.uid = m.uid WHERE u.nid = ".$nid);

			foreach($db_users as $account){
				$params['account'] = $account;
				$params['webform'] = $webform_mailer;
				$user_details = get_user_details($account);
				drupal_mail('webform_mailer', 'reminder', $account->mail, user_preferred_language($account), $params, $from, TRUE);
				$count++;
				$query = db_insert('webform_mailer_messages')
				->fields(array(
				  'nid' => $nid,
				  'uid' => $account->uid,
				  'message_time' => time(),
				  'type' => 'reminder',
				))->execute();		
			}

			$status = "reminded_".$count;
		}
		
		$query = db_update('webform_mailer')
			->fields(array(
				'status' => $status,
			))
			->condition('nid', $nid)
			->execute();
	}
}

function mailer_mail($key, &$message, $params) {
	$data['user'] = $params['account'];
	$options['language'] = $message['language'];
	user_mail_tokens($variables, $data, $options);
	switch($key) {
	case 'notify':
		$langcode = $message['language']->language;
		$message['subject'] = t('DØK Alumni', $variables, array('langcode' => $langcode));
		$message['body'][] = t("Hej Frække!", $variables, array('langcode' => $langcode));
        break;
	case 'reminder':
		$langcode = $message['language']->language;
		$message['subject'] = t('Notification from !site', $variables, array('langcode' => $langcode));
		$message['body'][] = t("Dear !username\n\nThere is new content available on the site.", $variables, array('langcode' => $langcode));
        break;
	}
}
function get_user_details($account){
	$type = $account->type;

	switch($type) {
		case 'drupal':
			return user_load($account->uid); 
		break;	
	}


}

