<?php

function doek_alumni_form_alter(&$form, &$form_state, $form_id){

	if(!($form_id == 'user_register_form' || $form_id == 'user_profile_form')){
		return;
	}
	global $user;

	if(is_array($user->roles) && in_array('administrator', $user->roles)){

		$form['alumni'] = array(
				'#type' 	=> 'fieldset', 
				'#title' 	=> t('DØK Alumni Oplysninger'),
				'#collapsible'	=> TRUE, 
				'#collapsed'	=> FALSE,
				'#weight'	=> 10,
				);
/*
		$form['alumni']['membership'] = array(
				'#type'		=> 'checkbox',
				'#options'	=> array('aktiv' => 1, 'inaktiv' => 2),
				'#title'	=> t('Alumni medlem'),
				'#description'	=> t('Om personen er medlem af Alumni'),
				);
*/
		$form['alumni']['payment_date'] = array(
				'#type'		=> 'date',
				'#title'	=> t('Betalingsdag'),
				'#description'	=> t('Data hvor personen har betalt for medlemsskab'),
				);
		
		$form['alumni']['member_id'] = array(
				'#type'		=> 'textfield',
				'#title'	=> t('Medlemsnummer'),
				'#description'	=> t('Brugerens medlemsnummer fra den gamle database'),
				'#maxlength'	=> 30,
				'#size'		=> 30,
				);

	}
		return $form;
}

function assign_membership_number(){

	$query = db_query("SELECT max(field_alumnimedlem_value) max FROM field_data_field_alumnimedlem");
	
	$result = $query->fetchObject();

	$current_number = $result->max;
	$counter = 0;

	$role_users = db_query("SELECT ur.uid FROM role r INNER JOIN users_roles ur ON r.rid = ur.rid WHERE r.name = 'Alumni'");

	foreach($role_users as $account){
		$account = user_load($account->uid);
		//	die(var_dump($account));	

		if(empty($account->field_alumnimedlem)){
			$edit = array(
				'field_alumnimedlem' => array(
					'und' => array(
						'0' => array(
							'value' => $current_number + 1,
							),
						),
					),
				);
			
			user_save($account, $edit);
			$counter++;
		}
	}
	echo $counter." Users updated";

	return true;
}

function doek_alumni_cron(){

	$status = false;

	$status = assign_membership_number();
	
	return $status;
}
