<?php
function gdl_menu() {
	$items['gdl/gdl'] = array('page callback' => 'gdl_gdl', 'access callback' => true);
	return $items;
}

function pushTjans(&$tjanser, $type, $dag, $title, $count) {
	for($i = 0; $i < $count; $i++) {
		array_push($tjanser, array('title' => $title, 'type' => $type, 'dag' => $dag));
	}
}

function getSlutRen() {
	$tjans = array();
	pushTjans($tjans, 'Rengøring', '', 'rengøre hytte A', 1);
	pushTjans($tjans, 'Rengøring', '', 'rengøre hytte B', 1);
	pushTjans($tjans, 'Rengøring', '', 'rengøre hytte C', 1);
	pushTjans($tjans, 'Rengøring', '', 'rengøre hytte D', 1);
	pushTjans($tjans, 'Rnegøring', '', 'rengøre hytte E', 1);
	pushTjans($tjans, 'Rengøring', '', 'rengøre indendørsområderne', 2);
	pushTjans($tjans, 'Rangøring', '', 'rengøre yderområderne', 2);
	pushTjans($tjans, 'Rengøring', '', 'rengøre køkkenet', 1);
	return $tjans;
}

function getTjanser() {
	$tjanser = array();
        for($i = 1; $i <= 5; $i++) {
                switch($i) {
                        case 1:
                                $dag = 'Fredag';
                                pushTjans($tjanser, 'Kiosk', $dag, 'Kiosk Opfyldning', 2);
                                break;

                        case 2:
                                $dag = 'Lørdag';
                                pushTjans($tjanser, 'Rengøring', $dag, 'Rengøring Indendørsområder', 5);
                                pushTjans($tjanser, 'Morgenmad', $dag, 'Morgenmad', 6);
                                pushTjans($tjanser, 'Opvask', $dag, 'Frokost Opvask', 6);
                                pushTjans($tjanser, 'Køkkenhold', $dag, 'Aftensmad Tilberedning', 10);
                                pushTjans($tjanser, 'Opvask', $dag, 'Aftensmad Opvask', 10);
                                pushTjans($tjanser, 'Kiosk', $dag, 'Kiosk Opfyldning', 2);
                                break;

                        case 3:
                                $dag = 'Søndag';
                                pushTjans($tjanser, 'Rengøring', $dag, 'Rengøring Indendørsområder', 5);
                                pushTjans($tjanser, 'Morgenmad', $dag, 'Morgenmad', 6);
                                pushTjans($tjanser, 'Opvask', $dag, 'Frokost Opvask', 6);
                                pushTjans($tjanser, 'Køkkenhold', $dag, 'Aftensmad Tilberedning', 10);
                                pushTjans($tjanser, 'Opvask', $dag, 'Aftensmad Opvask', 10);
                                pushTjans($tjanser, 'Kiosk', $dag, 'Kiosk Opfyldning', 2);
                                break;

                        case 4:
                                $dag = 'Mandag';
                                pushTjans($tjanser, 'Rengøring', $dag, 'Rengøring Indendørsområder', 5);
                                pushTjans($tjanser, 'Morgenmad', $dag, 'Morgenmad', 6);
                                pushTjans($tjanser, 'Opvask', $dag, 'Frokost Opvask', 6);
                                pushTjans($tjanser, 'Køkkenhold', $dag, 'Aftensmad Tilberedning', 10);
                                pushTjans($tjanser, 'Opvask', $dag, 'Aftensmad Opvask', 10);
                                pushTjans($tjanser, 'Kiosk', $dag, 'Kiosk Opfyldning', 2);
                                break;

                        case 5:
                                $dag = 'Tirsdag';
                                pushTjans($tjanser, 'Morgenmad', $dag, 'Morgenmad', 6);
                                break;
                }
	}
	return $tjanser;
}
function getWorkers($fraggler, $title, $dag) {
	$workers = array();
	foreach ($fraggler as $fraggle) {
		foreach ($fraggle['tjanser'] as $tjans) {
			if ($tjans['title'] == $title && $tjans['dag'] == $dag) {
				array_push($workers, $fraggle['navn']);
			}
		}
	}
	return $workers;
}

function getFraggler($productId) {
  $orders = commerce_order_load_multiple(array(), array('status' => 'pending'));
  $uids = array();
  foreach($orders as $order) {
    $skip = false;
    foreach($uids as $user) {
      if ($user['id'] == $order->uid) {
        $skip = true;;
      }
    }
    if ($skip) {
      continue;
    }
    foreach($order->commerce_line_items as $line_items) {
      foreach($line_items as $line_item) {
        $items = commerce_line_item_load($line_item['line_item_id']);
        foreach($items->commerce_product as $item) {
          foreach($item as $product_entity) {
            if ($product_entity['product_id'] == $productId) {
              $product = commerce_product_load($product_entity['product_id']);
              $name = field_get_items('user', user_load($order->uid), 'field_name');
              array_push($uids, array('id' => $order->uid, 'tjanser' => array(), 'navn' => mb_convert_encoding($name[0]['value'], 'ISO-8859-1', mb_detect_encoding($name[0]['value'], 'auto'))));
            }
          }
        }
      }
    }
  }
  return $uids;
}

function gdl_gdl() {
	$tjanser = getTjanser();
	$fraggler = getFraggler(24);
  foreach($tjanser as $tkey => $tjans) {
    uasort($fraggler, 'cmp');
    foreach($fraggler as $fkey => $fraggle) {
      if (isFraggleEligeble($fraggle, $tjans)) {
        array_push($fraggler[$fkey]['tjanser'], $tjans);
        break;
      }
    }
  }
  uasort($fraggler, 'cmp');
	printGDL($fraggler);
}

function isFraggleEligeble($fraggle, $tjans) {
  return true;
	foreach ($fraggle['tjanser'] as $fraggletjans) {
		if ($fraggletjans['type'] == $tjans['type'] || $fraggletjans['dag'] == $tjans['dag']) {
			return false;
		}
	}
	return true;
}

function cmp($a, $b) {
    if (count($a['tjanser']) == count($b['tjanser'])) {
        return 0;
    }
    return (count($a['tjanser']) < count($b['tjanser'])) ? -1 : 1;
}
function trimName($name, $maxlength) {
	$names = explode(" ", $name);
	$name = $names[sizeof($names)-1];
	unset($names[sizeof($names)-1]);
	$name .= ', '.implode(' ', $names);
	$name = substr($name, 0, $maxlength);
	return $name;
}

function pushRum(&$pladser, $hus, $title, $count) {
	for ($i = 0; $i < $count; $i++) {
		array_push($pladser, $title);
	}
}

function getPladser() {
	$pladser = array();
	//pushRum($pladser, 'Hytte A', 'A.1', 9); // For the ladies!
  pushRum($pladser, 'Hytte A', 'A.2', 9);
  pushRum($pladser, 'Hytte B', 'B.1', 9);
  pushRum($pladser, 'Hytte B', 'B.2', 9);
  pushRum($pladser, 'Hytte C', 'C.1', 9);
  pushRum($pladser, 'Hytte C', 'C.2', 9);
  pushRum($pladser, 'Hytte D', 'D.1', 9);
  pushRum($pladser, 'Hytte D', 'D.2', 9);
  pushRum($pladser, 'Hytte E', 'E.1', 9);
  pushRum($pladser, 'Hytte E', 'E.2', 9);
	return $pladser;
}

function getLadies() {
	$ladies = array('Louise Jylling', 'Trine Kølle', 'Simone Fitzwilliams', 'Amalie Sørensen Midskard', 'Victoria Handskemager Wagner', 'Katrine Refvem');
	return $ladies;
}

function printGDL($fraggler) {
  $tja = array('Kiosk Opfyldning', 'Rengøring Indendørsområder', 'Morgenmad', 'Frokost Opvask', 'Aftensmad Tilberedning', 'Aftensmad Opvask');
  $dage = array('Fredag', 'Lørdag', 'Søndag', 'Mandag', 'Tirsdag');
  echo '
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="da" lang="da">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<style type="text/css">td { vertical-align: top; } table { page-break-after: always; }
.container {
  position: relative;
}

.ticket {
  width: 640px;
}

p {
	font-family:"Lucida Console", Monaco, monospace;
	font-size:0.8em;
	line-height: 150%;
}

.destination{
  position: absolute;
  top: 150px;
  left: 70px;
}

.navn {
  position: absolute;
  top: 150px;
  left: 260px;
}

.plads {
  position: absolute;
  top: 200px;
  left: 70px;
}

.flynummer {
  position: absolute;
  top: 200px;
  left: 260px;
}

.afgangstid {
  position: absolute;
  top: 250px;
  left: 70px;
}

.dato {
  position: absolute;
  top: 250px;
  left: 260px;
}

.ankomst {
  position: absolute;
  top: 300px;
  left: 70px;
}

.wakeup {
  position: absolute;
  top: 415px;
  left: 70px;
  width: 230px;
}

.tilvalg {
  position: absolute;
  top: 415px;
  left: 350px;
  width: 240px;
}

.tjanser {
  position: absolute;
  top: 625px;
  left: 70px;
  width: 525px;
}

.clear {
	clear:both;
	
}
.page-break, .container {
	display:block;
	page-break-before:always;
}
</style>
</head>
<body><div>';
  foreach($dage as $dag) {
    echo "<h2>$dag</h2>";
    echo "<table><tr>";
    $i = 0;
    foreach($tja as $tjans) {
      if ($i%3 == 0) {
        echo "</tr><tr>";
      }
      echo "<td>";
      $workers = getWorkers($fraggler, $tjans, $dag);
      if (count($workers) > 0) {
      echo "<h3>$tjans</h3>";
      echo '<p>';
      foreach($workers as $worker) {
        echo $worker.'<br />';
      }
      echo '</p>';
    }
    echo "<br /></td>";
    $i++;
    }
    $rest = $i%3;
    for($i = 0; $i < $rest; $i++) {
      echo "<td></td>";
    }
    echo "</tr></table>";
  }
  echo '</div><div>';

  $pladser = getPladser();
  $ladies = getLadies();
  $slutTjanser = getSlutRen();
  $slutcount = count($slutTjanser);

  $i = 0;
  $j = 0;
  $beboere = array();
  
	sort($fraggler);
	$dest = 'Sunny Beach';
	$threshold = intval(count($fraggler) / 2) + 1;
	
	echo '<div id="container">';
  foreach($fraggler as $fraggle) {
		if ($j > $threshold) {
			$dest = 'Ibiza';
		}
    // FOrdel på slutrengøringstjanser.
    $slut = $slutTjanser[$j%$slutcount]['title'];
    echo '<br /><br />';
    
    // Fordel på værelser.
    if (array_search($fraggle['navn'], $ladies)) {
      $rum = 'A.1';
    }
    else {
      $rum = $pladser[$i];
      $i++;
    }
    array_push($beboere, array('navn' => $fraggle['navn'], 'rum' => $rum));
    
    
echo <<<END
END;
echo '
  <div class="container">
    <img src="/sites/default/files/boarding.png" class="ticket" />
    <div class="destination"><p>'.$dest.'</p></div> 
    <div class="navn"><p>'.$fraggle['navn'].'</p></div>
    <div class="clear">&nbsp;</div>
    <div class="plads"><p>'.$rum.'</p></div>
    <div class="flynummer"><p>50366FD</p></div>
    <div class="clear">&nbsp;</div>
    <div class="afgangstid"><p>10:30</p></div>
    <div class="dato"><p>24. August 2012</p></div>
    <div class="ankomst"><p>15:30ish</p></div>
    <div class="clear">&nbsp;</div>
    <div class="wakeup">
    	<p>
    	Lørdag: 9:00 <br/>
        Søndag: 9:00 <br/>
        Mandag: 9:00 <br/>
        Tirsdag: 9:00 <br/>
        <i>Vær oppe til tiden. Toiletterne i vejlederområdet trænger til vask!</i>
        </p>
    </div>
    <div class="tilvalg">
    <p>
    	Fredag: Bustur<br />
      Lørdag: Djøf Cup. \'90\'er\' fest<br/>
      Søndag: CBS 360*. \'For lækker til love\' fest<br/>
      Mandag: Kommunikation og find job. \'Romer\' fest<br/>
      Tirsdag: Party Bus
    </p>
    </div>
    <div class="clear">&nbsp;</div>
    <div class="tjanser">
    	<p>';
    	foreach ($fraggle['tjanser'] as $tjans) {
        echo $tjans['dag'].': '.$tjans['title'].'<br />';
    	}
      echo 'Under slutrengøringen skal du '.$slut.'.<br />
        <i>Skulle du af mystiske årsager udeblive fra en tjans, skal du glæde dig til vejledernes straf.</i>
        </p>
    </div>
  </div>
';
    $j++;
	}
echo '
</div>
';
    
    
    

  echo '<div style="page-break-after: always;"></div>';
  usort($beboere, 'compareArray');
  echo '<table>';
  foreach($beboere as $beboer) {
    echo '<tr><td>'.$beboer['navn'].'</td><td>'.$beboer['rum'] . '</td></tr>';
  }
  echo '</table>';
  echo '</div></body></html>';
}

function compareArray($a, $b) {
	if ($a['navn'] == $b['navn']) {
		return 0;
	}
	return ($a['navn'] < $b['navn']) ? -1 : 1;
}
?>
